/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cis272_project.View;

import Controller.Element;
import cis272_project.Model.ElementManager;
import com.sun.java.swing.plaf.motif.MotifLookAndFeel;
import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.LookAndFeel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.text.BadLocationException;
import javax.swing.text.StyledDocument;

/**
 *
 * @author GW
 */
public class FrameMain extends javax.swing.JFrame {

    /**
     * Creates new form FrameMain
     */
    private static final String TITLE = "W.E.B. EDITOR";

    private JFileChooser chooser;
    private Clipboard clipBoard;
    private String fileName;

    private Element element;

    public FrameMain() {
        init();
        initComponents();
        //--This will set the jeditorpane to displau html
        jEditorPane_Preview.setContentType("text/html");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpan_Main = new javax.swing.JPanel();
        jPanel_Control = new javax.swing.JPanel();
        jPanel_Default = new javax.swing.JPanel();
        jPanel_Default_HTML = new javax.swing.JPanel();
        jButton_Default_P = new javax.swing.JButton();
        jButton_Default_H1 = new javax.swing.JButton();
        jButton_Default_A = new javax.swing.JButton();
        jButton_Default_IMG = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jButton_Form = new javax.swing.JButton();
        jButton_BR = new javax.swing.JButton();
        jButton_TABLE = new javax.swing.JButton();
        jSeparator19 = new javax.swing.JSeparator();
        jButton_Default_DIV = new javax.swing.JButton();
        jButton_Default_SPAN = new javax.swing.JButton();
        jButton_Default_LI = new javax.swing.JButton();
        jButton_Default_UL = new javax.swing.JButton();
        jButton_Default_TR = new javax.swing.JButton();
        jButton_Default_TD = new javax.swing.JButton();
        jButton_HR = new javax.swing.JButton();
        jButton_Default_IFRAME = new javax.swing.JButton();
        jButton_Default_SPACE = new javax.swing.JButton();
        jPanel_Paragraph = new javax.swing.JPanel();
        jLabel_ParagraphName = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel_Heading = new javax.swing.JPanel();
        jPanel_Link = new javax.swing.JPanel();
        jPanel_Image = new javax.swing.JPanel();
        jpan_Editor = new javax.swing.JPanel();
        jtab_Main = new javax.swing.JTabbedPane();
        jTab_Source = new javax.swing.JScrollPane();
        jTextPane_Source = new javax.swing.JTextPane();
        jTab_Preview = new javax.swing.JScrollPane();
        jEditorPane_Preview = new javax.swing.JEditorPane();
        jToolBar_Main = new javax.swing.JToolBar();
        jbut_NewFile = new javax.swing.JButton();
        jbut_OpenFile = new javax.swing.JButton();
        jbut_SaveFile = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jbut_Browser = new javax.swing.JButton();
        jToolBar_Font = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jComboBox_Font = new javax.swing.JComboBox();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jbut_AlignLeft = new javax.swing.JButton();
        jbut_AlignCenter = new javax.swing.JButton();
        jbut_AlignRight = new javax.swing.JButton();
        jbut_AlignFull = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jMenuBar_Main = new javax.swing.JMenuBar();
        jmenu_File = new javax.swing.JMenu();
        jmenu_newFile = new javax.swing.JMenuItem();
        jmenu_openFile = new javax.swing.JMenuItem();
        jmenu_saveFile = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jmenu_Exit = new javax.swing.JMenuItem();
        jmenu_Edit = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jmenu_Copy = new javax.swing.JMenuItem();
        jmenu_Paste = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem_H1 = new javax.swing.JMenuItem();
        jMenuItem_H2 = new javax.swing.JMenuItem();
        jMenuItem_H3 = new javax.swing.JMenuItem();
        jMenuItem_H4 = new javax.swing.JMenuItem();
        jMenuItem_H5 = new javax.swing.JMenuItem();
        jMenuItem_H6 = new javax.swing.JMenuItem();
        jMenuItem_Paragraoh = new javax.swing.JMenuItem();
        jMenuItem_Link = new javax.swing.JMenuItem();
        jMenuItem_IMG = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem_FormPlain = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Breakline = new javax.swing.JMenuItem();
        jMenuItem_HorizonLine = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Title = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jmenu_Help = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu_Style = new javax.swing.JMenu();
        jMenu_Nimbus = new javax.swing.JMenuItem();
        jMenu_Metal = new javax.swing.JMenuItem();
        jMenu_Motif = new javax.swing.JMenuItem();
        jMenu_WindowsClassic = new javax.swing.JMenuItem();
        jMenu_Windows = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmenu_showAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpan_Main.setPreferredSize(new java.awt.Dimension(1024, 800));

        jPanel_Control.setLayout(new java.awt.CardLayout());

        jPanel_Default_HTML.setBorder(javax.swing.BorderFactory.createTitledBorder("HTML"));

        jButton_Default_P.setText("<p>");
        jButton_Default_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Default_PActionPerformed(evt);
            }
        });

        jButton_Default_H1.setText("<h1>");
        jButton_Default_H1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Default_H1ActionPerformed(evt);
            }
        });

        jButton_Default_A.setText("<a>");
        jButton_Default_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Default_AActionPerformed(evt);
            }
        });

        jButton_Default_IMG.setText("<img>");
        jButton_Default_IMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Default_IMGActionPerformed(evt);
            }
        });

        jButton_Form.setText("<form>");
        jButton_Form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FormActionPerformed(evt);
            }
        });

        jButton_BR.setText("<br>");
        jButton_BR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BRActionPerformed(evt);
            }
        });

        jButton_TABLE.setText("<table>");
        jButton_TABLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TABLEActionPerformed(evt);
            }
        });

        jButton_Default_DIV.setText("<div>");
        jButton_Default_DIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Default_DIVActionPerformed(evt);
            }
        });

        jButton_Default_SPAN.setText("<span>");
        jButton_Default_SPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Default_SPANActionPerformed(evt);
            }
        });

        jButton_Default_LI.setText("<li>");
        jButton_Default_LI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Default_LIActionPerformed(evt);
            }
        });

        jButton_Default_UL.setText("<ul>");
        jButton_Default_UL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Default_ULActionPerformed(evt);
            }
        });

        jButton_Default_TR.setText("<tr>");
        jButton_Default_TR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Default_TRActionPerformed(evt);
            }
        });

        jButton_Default_TD.setText("<td>");
        jButton_Default_TD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Default_TDActionPerformed(evt);
            }
        });

        jButton_HR.setText("<hr>");
        jButton_HR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HRActionPerformed(evt);
            }
        });

        jButton_Default_IFRAME.setText("<iframe>");
        jButton_Default_IFRAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Default_IFRAMEActionPerformed(evt);
            }
        });

        jButton_Default_SPACE.setText("&nbsp; (Space)");
        jButton_Default_SPACE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Default_SPACEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Default_HTMLLayout = new javax.swing.GroupLayout(jPanel_Default_HTML);
        jPanel_Default_HTML.setLayout(jPanel_Default_HTMLLayout);
        jPanel_Default_HTMLLayout.setHorizontalGroup(
            jPanel_Default_HTMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(jPanel_Default_HTMLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Default_HTMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Default_IFRAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_BR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Form, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_Default_HTMLLayout.createSequentialGroup()
                        .addComponent(jButton_Default_P, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Default_H1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_Default_HTMLLayout.createSequentialGroup()
                        .addComponent(jButton_Default_A, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Default_IMG, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_TABLE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator19)
                    .addGroup(jPanel_Default_HTMLLayout.createSequentialGroup()
                        .addComponent(jButton_Default_DIV, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Default_SPAN, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_Default_HTMLLayout.createSequentialGroup()
                        .addComponent(jButton_Default_UL, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Default_LI, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_Default_HTMLLayout.createSequentialGroup()
                        .addComponent(jButton_Default_TR, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Default_TD, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_Default_SPACE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_HR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_Default_HTMLLayout.setVerticalGroup(
            jPanel_Default_HTMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Default_HTMLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Default_HTMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Default_P)
                    .addComponent(jButton_Default_H1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Default_HTMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Default_A)
                    .addComponent(jButton_Default_IMG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Form)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_BR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_HR)
                .addGap(11, 11, 11)
                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Default_HTMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Default_DIV)
                    .addComponent(jButton_Default_SPAN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Default_HTMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Default_UL)
                    .addComponent(jButton_Default_LI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_TABLE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Default_HTMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Default_TR)
                    .addComponent(jButton_Default_TD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Default_IFRAME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Default_SPACE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_Default_P.getAccessibleContext().setAccessibleDescription("Paragraph");
        jButton_Default_H1.getAccessibleContext().setAccessibleDescription("Heading 1");
        jButton_Default_A.getAccessibleContext().setAccessibleDescription("Link");
        jButton_Default_IMG.getAccessibleContext().setAccessibleDescription("Image");

        javax.swing.GroupLayout jPanel_DefaultLayout = new javax.swing.GroupLayout(jPanel_Default);
        jPanel_Default.setLayout(jPanel_DefaultLayout);
        jPanel_DefaultLayout.setHorizontalGroup(
            jPanel_DefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DefaultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Default_HTML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_DefaultLayout.setVerticalGroup(
            jPanel_DefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DefaultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Default_HTML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        jPanel_Control.add(jPanel_Default, "card2");

        jLabel_ParagraphName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ParagraphName.setText("Paragraph");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Attributes"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_ParagraphLayout = new javax.swing.GroupLayout(jPanel_Paragraph);
        jPanel_Paragraph.setLayout(jPanel_ParagraphLayout);
        jPanel_ParagraphLayout.setHorizontalGroup(
            jPanel_ParagraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator18, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel_ParagraphLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ParagraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_ParagraphName, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_ParagraphLayout.setVerticalGroup(
            jPanel_ParagraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ParagraphLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_ParagraphName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(467, Short.MAX_VALUE))
        );

        jPanel_Control.add(jPanel_Paragraph, "card3");

        javax.swing.GroupLayout jPanel_HeadingLayout = new javax.swing.GroupLayout(jPanel_Heading);
        jPanel_Heading.setLayout(jPanel_HeadingLayout);
        jPanel_HeadingLayout.setHorizontalGroup(
            jPanel_HeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        jPanel_HeadingLayout.setVerticalGroup(
            jPanel_HeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );

        jPanel_Control.add(jPanel_Heading, "card4");

        javax.swing.GroupLayout jPanel_LinkLayout = new javax.swing.GroupLayout(jPanel_Link);
        jPanel_Link.setLayout(jPanel_LinkLayout);
        jPanel_LinkLayout.setHorizontalGroup(
            jPanel_LinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        jPanel_LinkLayout.setVerticalGroup(
            jPanel_LinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );

        jPanel_Control.add(jPanel_Link, "card5");

        javax.swing.GroupLayout jPanel_ImageLayout = new javax.swing.GroupLayout(jPanel_Image);
        jPanel_Image.setLayout(jPanel_ImageLayout);
        jPanel_ImageLayout.setHorizontalGroup(
            jPanel_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        jPanel_ImageLayout.setVerticalGroup(
            jPanel_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );

        jPanel_Control.add(jPanel_Image, "card6");

        jtab_Main.setDoubleBuffered(true);
        jtab_Main.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtab_MainFocusGained(evt);
            }
        });

        jTab_Source.setViewportView(jTextPane_Source);

        jtab_Main.addTab("Source", jTab_Source);

        jTab_Preview.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTab_PreviewComponentShown(evt);
            }
        });

        jEditorPane_Preview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jEditorPane_PreviewMouseEntered(evt);
            }
        });
        jTab_Preview.setViewportView(jEditorPane_Preview);

        jtab_Main.addTab("Preview", jTab_Preview);

        javax.swing.GroupLayout jpan_EditorLayout = new javax.swing.GroupLayout(jpan_Editor);
        jpan_Editor.setLayout(jpan_EditorLayout);
        jpan_EditorLayout.setHorizontalGroup(
            jpan_EditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtab_Main, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jpan_EditorLayout.setVerticalGroup(
            jpan_EditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtab_Main, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jtab_Main.getAccessibleContext().setAccessibleName("tab_Preview");

        jToolBar_Main.setFloatable(false);
        jToolBar_Main.setRollover(true);

        jbut_NewFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/New document.png"))); // NOI18N
        jbut_NewFile.setText("New File");
        jbut_NewFile.setToolTipText("New File");
        jbut_NewFile.setFocusable(false);
        jbut_NewFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbut_NewFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar_Main.add(jbut_NewFile);

        jbut_OpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/folder.png"))); // NOI18N
        jbut_OpenFile.setText("Open File");
        jbut_OpenFile.setToolTipText("Open File");
        jbut_OpenFile.setFocusable(false);
        jbut_OpenFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbut_OpenFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbut_OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbut_OpenFileActionPerformed(evt);
            }
        });
        jToolBar_Main.add(jbut_OpenFile);

        jbut_SaveFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/save.png"))); // NOI18N
        jbut_SaveFile.setText("Save File");
        jbut_SaveFile.setToolTipText("Save File");
        jbut_SaveFile.setFocusable(false);
        jbut_SaveFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbut_SaveFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar_Main.add(jbut_SaveFile);
        jToolBar_Main.add(jSeparator3);

        jbut_Browser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/globe.png"))); // NOI18N
        jbut_Browser.setText("  Browser");
        jbut_Browser.setToolTipText("Browser");
        jbut_Browser.setFocusable(false);
        jbut_Browser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbut_Browser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbut_Browser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbut_BrowserActionPerformed(evt);
            }
        });
        jToolBar_Main.add(jbut_Browser);

        jToolBar_Font.setFloatable(false);
        jToolBar_Font.setRollover(true);

        jLabel1.setText("  Font: ");
        jToolBar_Font.add(jLabel1);
        jToolBar_Font.add(jSeparator9);

        jComboBox_Font.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arial", "Times New Roman", "Comics" }));
        jComboBox_Font.setToolTipText("Fonts");
        jToolBar_Font.add(jComboBox_Font);
        jToolBar_Font.add(jSeparator10);

        jbut_AlignLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/text_align_left.png"))); // NOI18N
        jbut_AlignLeft.setFocusable(false);
        jbut_AlignLeft.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbut_AlignLeft.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar_Font.add(jbut_AlignLeft);

        jbut_AlignCenter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/text_align_center.png"))); // NOI18N
        jbut_AlignCenter.setFocusable(false);
        jbut_AlignCenter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbut_AlignCenter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar_Font.add(jbut_AlignCenter);

        jbut_AlignRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/text_align_right.png"))); // NOI18N
        jbut_AlignRight.setFocusable(false);
        jbut_AlignRight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbut_AlignRight.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar_Font.add(jbut_AlignRight);

        jbut_AlignFull.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/text_align_full.png"))); // NOI18N
        jbut_AlignFull.setFocusable(false);
        jbut_AlignFull.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbut_AlignFull.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar_Font.add(jbut_AlignFull);
        jToolBar_Font.add(jSeparator11);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/color.png"))); // NOI18N
        jButton1.setToolTipText("Color Manager");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar_Font.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/highlight.png"))); // NOI18N
        jButton2.setToolTipText("HighLight");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar_Font.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/smaller.png"))); // NOI18N
        jButton3.setToolTipText("Smaller Font");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar_Font.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/bigger.png"))); // NOI18N
        jButton4.setToolTipText("Bigger Font");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar_Font.add(jButton4);
        jToolBar_Font.add(jSeparator12);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/Bold.png"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar_Font.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/Italic.png"))); // NOI18N
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar_Font.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/Underline.png"))); // NOI18N
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar_Font.add(jButton7);

        javax.swing.GroupLayout jpan_MainLayout = new javax.swing.GroupLayout(jpan_Main);
        jpan_Main.setLayout(jpan_MainLayout);
        jpan_MainLayout.setHorizontalGroup(
            jpan_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addComponent(jToolBar_Font, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpan_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpan_Editor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpan_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Control, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpan_MainLayout.setVerticalGroup(
            jpan_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpan_MainLayout.createSequentialGroup()
                .addComponent(jToolBar_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar_Font, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpan_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpan_MainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpan_Editor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpan_MainLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_Control, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jmenu_File.setText("File");

        jmenu_newFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jmenu_newFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/New document.png"))); // NOI18N
        jmenu_newFile.setText("New File");
        jmenu_File.add(jmenu_newFile);

        jmenu_openFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jmenu_openFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/folder.png"))); // NOI18N
        jmenu_openFile.setText("Open File");
        jmenu_openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_openFileActionPerformed(evt);
            }
        });
        jmenu_File.add(jmenu_openFile);

        jmenu_saveFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmenu_saveFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/save.png"))); // NOI18N
        jmenu_saveFile.setText("Save File");
        jmenu_File.add(jmenu_saveFile);
        jmenu_File.add(jSeparator1);

        jMenu5.setText("Export");

        jMenuItem9.setText("HTML");
        jMenu5.add(jMenuItem9);

        jMenuItem10.setText("CSS");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jmenu_File.add(jMenu5);

        jMenu13.setText("Import");

        jMenuItem44.setText("HTML");
        jMenu13.add(jMenuItem44);

        jMenuItem45.setText("CSS");
        jMenu13.add(jMenuItem45);

        jmenu_File.add(jMenu13);
        jmenu_File.add(jSeparator6);

        jmenu_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/Exit.png"))); // NOI18N
        jmenu_Exit.setText("Exit");
        jmenu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_ExitActionPerformed(evt);
            }
        });
        jmenu_File.add(jmenu_Exit);

        jMenuBar_Main.add(jmenu_File);

        jmenu_Edit.setText("Edit");

        jMenuItem20.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/edit-cut.png"))); // NOI18N
        jMenuItem20.setText("Cut");
        jmenu_Edit.add(jMenuItem20);

        jmenu_Copy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmenu_Copy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/Copy.png"))); // NOI18N
        jmenu_Copy.setText("Copy");
        jmenu_Copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_CopyActionPerformed(evt);
            }
        });
        jmenu_Edit.add(jmenu_Copy);

        jmenu_Paste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jmenu_Paste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/Paste.png"))); // NOI18N
        jmenu_Paste.setText("Paste");
        jmenu_Paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_PasteActionPerformed(evt);
            }
        });
        jmenu_Edit.add(jmenu_Paste);

        jMenuBar_Main.add(jmenu_Edit);

        jMenu1.setText("View");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/Text.png"))); // NOI18N
        jMenuItem4.setText("Source");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/Display.png"))); // NOI18N
        jMenuItem5.setText("Preview");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/globe.png"))); // NOI18N
        jMenuItem6.setText("Browser");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar_Main.add(jMenu1);

        jMenu2.setText("Format");

        jMenu7.setText("Font");

        jMenuItem21.setText("Arial");
        jMenu7.add(jMenuItem21);

        jMenu2.add(jMenu7);

        jMenu8.setText("Size");

        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/smaller.png"))); // NOI18N
        jMenuItem24.setText("Smaller Font");
        jMenu8.add(jMenuItem24);

        jMenuItem25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/bigger.png"))); // NOI18N
        jMenuItem25.setText("Bigger Font");
        jMenu8.add(jMenuItem25);

        jMenu2.add(jMenu8);
        jMenu2.add(jSeparator8);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/Bold.png"))); // NOI18N
        jMenuItem19.setText("Bold");
        jMenu2.add(jMenuItem19);

        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/Italic.png"))); // NOI18N
        jMenuItem22.setText("Italic");
        jMenu2.add(jMenuItem22);

        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/Underline.png"))); // NOI18N
        jMenuItem23.setText("Underline");
        jMenu2.add(jMenuItem23);
        jMenu2.add(jSeparator13);

        jMenuItem26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/color.png"))); // NOI18N
        jMenuItem26.setText("Color");
        jMenu2.add(jMenuItem26);

        jMenuItem27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/highlight.png"))); // NOI18N
        jMenuItem27.setText("Highlight");
        jMenu2.add(jMenuItem27);

        jMenuBar_Main.add(jMenu2);

        jMenu3.setText("HTML");

        jMenu6.setText("Headings");

        jMenuItem_H1.setText("Heading 1");
        jMenuItem_H1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_H1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_H1);

        jMenuItem_H2.setText("Heading 2");
        jMenuItem_H2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_H2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_H2);

        jMenuItem_H3.setText("Heading 3");
        jMenuItem_H3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_H3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_H3);

        jMenuItem_H4.setText("Heading 4");
        jMenuItem_H4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_H4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_H4);

        jMenuItem_H5.setText("Heading 5");
        jMenuItem_H5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_H5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_H5);

        jMenuItem_H6.setText("Heading 6");
        jMenuItem_H6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_H6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_H6);

        jMenu3.add(jMenu6);

        jMenuItem_Paragraoh.setText("Paragraph");
        jMenuItem_Paragraoh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ParagraohActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_Paragraoh);

        jMenuItem_Link.setText("Link");
        jMenuItem_Link.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_LinkActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_Link);

        jMenuItem_IMG.setText("Image");
        jMenuItem_IMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_IMGActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_IMG);
        jMenu3.add(jSeparator7);

        jMenu9.setText("Form");

        jMenuItem_FormPlain.setText("Plain Form");
        jMenuItem_FormPlain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_FormPlainActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem_FormPlain);
        jMenu9.add(jSeparator15);

        jMenu3.add(jMenu9);

        jMenuItem_Breakline.setText("Break Line");
        jMenuItem_Breakline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_BreaklineActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_Breakline);

        jMenuItem_HorizonLine.setText("Horizon Line");
        jMenuItem_HorizonLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_HorizonLineActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_HorizonLine);
        jMenu3.add(jSeparator14);

        jMenuItem_Title.setText("Title");
        jMenuItem_Title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TitleActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_Title);

        jMenuItem31.setText("List");
        jMenu3.add(jMenuItem31);

        jMenuItem32.setText("Table");
        jMenu3.add(jMenuItem32);

        jMenuItem35.setText("Div");
        jMenu3.add(jMenuItem35);

        jMenuItem36.setText("Span");
        jMenu3.add(jMenuItem36);

        jMenuItem34.setText("Iframe");
        jMenu3.add(jMenuItem34);
        jMenu3.add(jSeparator16);

        jMenuItem37.setText("Script");
        jMenu3.add(jMenuItem37);

        jMenu10.setText("Entities");

        jMenuItem1.setText("Space");
        jMenu10.add(jMenuItem1);

        jMenu3.add(jMenu10);

        jMenuItem38.setText("Character set");
        jMenu3.add(jMenuItem38);

        jMenuBar_Main.add(jMenu3);

        jMenu4.setText("CSS");

        jMenu11.setText("Background");

        jMenuItem39.setText("Color");
        jMenu11.add(jMenuItem39);

        jMenuItem40.setText("Image");
        jMenu11.add(jMenuItem40);
        jMenu11.add(jSeparator17);

        jMenuItem41.setText("Attachment");
        jMenu11.add(jMenuItem41);

        jMenuItem42.setText("Position");
        jMenu11.add(jMenuItem42);

        jMenuItem43.setText("Repeat");
        jMenu11.add(jMenuItem43);

        jMenu4.add(jMenu11);

        jMenu12.setText("Text");
        jMenu4.add(jMenu12);

        jMenuBar_Main.add(jMenu4);

        jmenu_Help.setText("Help");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/Help book.png"))); // NOI18N
        jMenuItem7.setText("Help");
        jmenu_Help.add(jMenuItem7);

        jMenu_Style.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/picture.png"))); // NOI18N
        jMenu_Style.setText("Style");

        jMenu_Nimbus.setText("Nimbus");
        jMenu_Nimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_NimbusActionPerformed(evt);
            }
        });
        jMenu_Style.add(jMenu_Nimbus);

        jMenu_Metal.setText("Metal");
        jMenu_Metal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_MetalActionPerformed(evt);
            }
        });
        jMenu_Style.add(jMenu_Metal);

        jMenu_Motif.setText("Motif");
        jMenu_Motif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_MotifActionPerformed(evt);
            }
        });
        jMenu_Style.add(jMenu_Motif);

        jMenu_WindowsClassic.setText("WindowsClassic");
        jMenu_WindowsClassic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_WindowsClassicActionPerformed(evt);
            }
        });
        jMenu_Style.add(jMenu_WindowsClassic);

        jMenu_Windows.setText("Windows");
        jMenu_Windows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_WindowsActionPerformed(evt);
            }
        });
        jMenu_Style.add(jMenu_Windows);

        jmenu_Help.add(jMenu_Style);
        jmenu_Help.add(jSeparator2);

        jmenu_showAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis272_project/Assets/info.png"))); // NOI18N
        jmenu_showAbout.setText("About");
        jmenu_showAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_showAboutActionPerformed(evt);
            }
        });
        jmenu_Help.add(jmenu_showAbout);

        jMenuBar_Main.add(jmenu_Help);

        setJMenuBar(jMenuBar_Main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpan_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpan_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenu_openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_openFileActionPerformed
        openFile();
    }//GEN-LAST:event_jmenu_openFileActionPerformed

    private void jmenu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_ExitActionPerformed
        // A quick close operation TODO: ask to save before quitting.
        System.exit(0);
    }//GEN-LAST:event_jmenu_ExitActionPerformed

    private void jmenu_showAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_showAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "This software was developed by Daniel Sega Mattos as a open-source project.\n"
                + "Special Thanks to www.iconfinder.com and www.small-icons.com for icons.", "About: W.E.B. Editor", WIDTH, null);
    }//GEN-LAST:event_jmenu_showAboutActionPerformed

    private void jmenu_PasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_PasteActionPerformed
        String result = "No Value";
        clipBoard = Toolkit.getDefaultToolkit().getSystemClipboard();
        Transferable transClip = clipBoard.getContents(null);

        if (transClip != null) {
            if (transClip.isDataFlavorSupported(DataFlavor.stringFlavor)) {
                try {
                    result = (String) transClip.getTransferData(DataFlavor.stringFlavor);
                } catch (UnsupportedFlavorException | IOException e) {
                    e.printStackTrace();
                }
            }
        }
        jTextPane_Source.setText(result);
    }//GEN-LAST:event_jmenu_PasteActionPerformed

    private void jmenu_CopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_CopyActionPerformed
        //TODO: Select text
        clipBoard = Toolkit.getDefaultToolkit().getSystemClipboard();
        Transferable tText = new StringSelection("test");
        clipBoard.setContents(tText, null);
    }//GEN-LAST:event_jmenu_CopyActionPerformed

    private void jMenu_MetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_MetalActionPerformed
        changeLookAndFeel(new MetalLookAndFeel());
    }//GEN-LAST:event_jMenu_MetalActionPerformed

    private void jMenu_NimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_NimbusActionPerformed
        changeLookAndFeel(new javax.swing.plaf.nimbus.NimbusLookAndFeel());
    }//GEN-LAST:event_jMenu_NimbusActionPerformed

    private void jMenu_MotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_MotifActionPerformed
        changeLookAndFeel(new MotifLookAndFeel());
    }//GEN-LAST:event_jMenu_MotifActionPerformed

    private void jMenu_WindowsClassicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_WindowsClassicActionPerformed
        changeLookAndFeel(new WindowsClassicLookAndFeel());
    }//GEN-LAST:event_jMenu_WindowsClassicActionPerformed

    private void jMenu_WindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_WindowsActionPerformed
        changeLookAndFeel(new WindowsLookAndFeel());
    }//GEN-LAST:event_jMenu_WindowsActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jbut_OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbut_OpenFileActionPerformed
        openFile();
    }//GEN-LAST:event_jbut_OpenFileActionPerformed

    private void jMenuItem_BreaklineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_BreaklineActionPerformed
        addSingleCommand(jPanel_Default_HTML, "br");
    }//GEN-LAST:event_jMenuItem_BreaklineActionPerformed

    private void jMenuItem_TitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TitleActionPerformed
        addCommand(jPanel_Default_HTML, ElementManager.Type.title);
    }//GEN-LAST:event_jMenuItem_TitleActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jtab_Main.setSelectedIndex(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jtab_Main.setSelectedIndex(1);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        openBrowser();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jbut_BrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbut_BrowserActionPerformed
        openBrowser();
    }//GEN-LAST:event_jbut_BrowserActionPerformed

    private void jtab_MainFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtab_MainFocusGained

    }//GEN-LAST:event_jtab_MainFocusGained

    //--This event will display the HTML as soon as the tab is displayed
    private void jTab_PreviewComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTab_PreviewComponentShown
        if (jTextPane_Source.getText() != null) {
            jEditorPane_Preview.setText(jTextPane_Source.getText());
        }
    }//GEN-LAST:event_jTab_PreviewComponentShown

    private void jEditorPane_PreviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditorPane_PreviewMouseEntered
        //addElement(ElementManager.Type.p);
    }//GEN-LAST:event_jEditorPane_PreviewMouseEntered

    private void jMenuItem_ParagraohActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ParagraohActionPerformed
        addCommand(jPanel_Paragraph, ElementManager.Type.p);
    }//GEN-LAST:event_jMenuItem_ParagraohActionPerformed

    private void jMenuItem_H1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_H1ActionPerformed
        addCommand(jPanel_Heading, ElementManager.Type.h1);
    }//GEN-LAST:event_jMenuItem_H1ActionPerformed

    private void jButton_Default_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Default_PActionPerformed
        addCommand(jPanel_Paragraph, ElementManager.Type.p);
    }//GEN-LAST:event_jButton_Default_PActionPerformed

    private void jButton_Default_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Default_AActionPerformed
        addCommand(jPanel_Link, ElementManager.Type.a);
    }//GEN-LAST:event_jButton_Default_AActionPerformed

    private void jButton_Default_H1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Default_H1ActionPerformed
        addCommand(jPanel_Heading, ElementManager.Type.h1);
    }//GEN-LAST:event_jButton_Default_H1ActionPerformed

    private void jButton_Default_IMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Default_IMGActionPerformed
        addCommand(jPanel_Image, ElementManager.Type.img);
    }//GEN-LAST:event_jButton_Default_IMGActionPerformed

    private void jButton_Default_DIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Default_DIVActionPerformed
        addCommand(jPanel_Default_HTML, ElementManager.Type.div);
    }//GEN-LAST:event_jButton_Default_DIVActionPerformed

    private void jButton_Default_SPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Default_SPANActionPerformed
        addCommand(jPanel_Default_HTML, ElementManager.Type.span);
    }//GEN-LAST:event_jButton_Default_SPANActionPerformed

    private void jButton_Default_LIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Default_LIActionPerformed
        addCommand(jPanel_Default_HTML, ElementManager.Type.li);
    }//GEN-LAST:event_jButton_Default_LIActionPerformed

    private void jButton_Default_ULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Default_ULActionPerformed
        addCommand(jPanel_Default_HTML, ElementManager.Type.ul);
    }//GEN-LAST:event_jButton_Default_ULActionPerformed

    private void jButton_Default_TRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Default_TRActionPerformed
        addCommand(jPanel_Default_HTML, ElementManager.Type.tr);
    }//GEN-LAST:event_jButton_Default_TRActionPerformed

    private void jButton_Default_TDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Default_TDActionPerformed
        addCommand(jPanel_Default_HTML, ElementManager.Type.td);
    }//GEN-LAST:event_jButton_Default_TDActionPerformed

    private void jButton_Default_IFRAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Default_IFRAMEActionPerformed
        addCommand(jPanel_Default_HTML, ElementManager.Type.iframe);
    }//GEN-LAST:event_jButton_Default_IFRAMEActionPerformed

    private void jButton_FormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FormActionPerformed
        addCommand(jPanel_Default_HTML, ElementManager.Type.form);
    }//GEN-LAST:event_jButton_FormActionPerformed

    private void jButton_BRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BRActionPerformed
        addSingleCommand(jPanel_Default_HTML, "br");
    }//GEN-LAST:event_jButton_BRActionPerformed

    private void jButton_TABLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TABLEActionPerformed
        addCommand(jPanel_Default_HTML, ElementManager.Type.table);
    }//GEN-LAST:event_jButton_TABLEActionPerformed

    private void jButton_HRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HRActionPerformed
        addSingleCommand(jPanel_Default_HTML, "hr");
    }//GEN-LAST:event_jButton_HRActionPerformed

    private void jButton_Default_SPACEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Default_SPACEActionPerformed
        addEntity("&nbsp");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Default_SPACEActionPerformed

    private void jMenuItem_H2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_H2ActionPerformed
        addCommand(jPanel_Heading, ElementManager.Type.h2);
    }//GEN-LAST:event_jMenuItem_H2ActionPerformed

    private void jMenuItem_H3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_H3ActionPerformed
        addCommand(jPanel_Heading, ElementManager.Type.h3);
    }//GEN-LAST:event_jMenuItem_H3ActionPerformed

    private void jMenuItem_H4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_H4ActionPerformed
        addCommand(jPanel_Heading, ElementManager.Type.h4);
    }//GEN-LAST:event_jMenuItem_H4ActionPerformed

    private void jMenuItem_H5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_H5ActionPerformed
        addCommand(jPanel_Heading, ElementManager.Type.h5);
    }//GEN-LAST:event_jMenuItem_H5ActionPerformed

    private void jMenuItem_H6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_H6ActionPerformed
        addCommand(jPanel_Heading, ElementManager.Type.h1);
    }//GEN-LAST:event_jMenuItem_H6ActionPerformed

    private void jMenuItem_LinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_LinkActionPerformed
        addCommand(jPanel_Link, ElementManager.Type.a);
    }//GEN-LAST:event_jMenuItem_LinkActionPerformed

    private void jMenuItem_IMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_IMGActionPerformed
        addCommand(jPanel_Image, ElementManager.Type.img);
    }//GEN-LAST:event_jMenuItem_IMGActionPerformed

    private void jMenuItem_FormPlainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_FormPlainActionPerformed
        addCommand(jPanel_Default_HTML, ElementManager.Type.form);
    }//GEN-LAST:event_jMenuItem_FormPlainActionPerformed

    private void jMenuItem_HorizonLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_HorizonLineActionPerformed
        addSingleCommand(jPanel_Default_HTML, "hr");
    }//GEN-LAST:event_jMenuItem_HorizonLineActionPerformed

    //--This will change the style of the application
    private void changeLookAndFeel(LookAndFeel laf) {
        try {
            UIManager.setLookAndFeel(laf);
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FrameMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //--Open File system
    private void openFile() {
        chooser.setFileFilter(new FileNameExtensionFilter("HTML and CSS", "HTML", "CSS"));
        int r_Value = chooser.showOpenDialog(this);
        if (r_Value == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: "
                    + chooser.getSelectedFile().getName());
        }
    }

    //--This will open the default browser
    private void openBrowser() {
        String fileLocation = "www.google.com";
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new URI(fileLocation));
            } catch (IOException | URISyntaxException ex) {
                Logger.getLogger(FrameMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    //--This will add simple elements
    private void addElement(ElementManager.Type type) {
        StyledDocument doc = jTextPane_Source.getStyledDocument();
        int pos = jTextPane_Source.getCaretPosition();
          if (jTextPane_Source.getSelectedText() == null) {
            try {
                doc.insertString(pos, "<" + type.name() + "> </" + type.name() + ">", null);
            } catch (BadLocationException ex) {
                Logger.getLogger(FrameMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (!jTextPane_Source.getSelectedText().isEmpty()) {
            String temp = element.addSingleElements(jTextPane_Source.getSelectedText(), type);
            try {
                doc.insertString(pos - temp.length(), "<" + type.name() + "> </" + type.name() + ">", null);
            } catch (BadLocationException ex) {
                Logger.getLogger(FrameMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    

    //--This will add functions to the buttons
    private void addCommand(JPanel pane, ElementManager.Type type) {
        jPanel_Control.removeAll();
        jPanel_Control.add(pane);
        jPanel_Control.repaint();
        jPanel_Control.revalidate();
        addElement(type);
    }

    private void addSingleCommand(JPanel pane, String type){
        jPanel_Control.removeAll();
        jPanel_Control.add(pane);
        jPanel_Control.repaint();
        jPanel_Control.revalidate();
        
        StyledDocument doc = jTextPane_Source.getStyledDocument();
        int pos = jTextPane_Source.getCaretPosition();
        if (jTextPane_Source.getSelectedText() == null) {
            try {
                doc.insertString(pos, "<" + type + ">", null);
            } catch (BadLocationException ex) {
                Logger.getLogger(FrameMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void addEntity(String type){
        StyledDocument doc = jTextPane_Source.getStyledDocument();
        int pos = jTextPane_Source.getCaretPosition();
        if (jTextPane_Source.getSelectedText() == null) {
            try {
                doc.insertString(pos,  type + ";", null);
            } catch (BadLocationException ex) {
                Logger.getLogger(FrameMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    //--My Initiallizer
    private void init() {
        setTitle(TITLE);
        chooser = new JFileChooser();
        element = new Element();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton_BR;
    private javax.swing.JButton jButton_Default_A;
    private javax.swing.JButton jButton_Default_DIV;
    private javax.swing.JButton jButton_Default_H1;
    private javax.swing.JButton jButton_Default_IFRAME;
    private javax.swing.JButton jButton_Default_IMG;
    private javax.swing.JButton jButton_Default_LI;
    private javax.swing.JButton jButton_Default_P;
    private javax.swing.JButton jButton_Default_SPACE;
    private javax.swing.JButton jButton_Default_SPAN;
    private javax.swing.JButton jButton_Default_TD;
    private javax.swing.JButton jButton_Default_TR;
    private javax.swing.JButton jButton_Default_UL;
    private javax.swing.JButton jButton_Form;
    private javax.swing.JButton jButton_HR;
    private javax.swing.JButton jButton_TABLE;
    private javax.swing.JComboBox jComboBox_Font;
    private javax.swing.JEditorPane jEditorPane_Preview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_ParagraphName;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar_Main;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem_Breakline;
    private javax.swing.JMenuItem jMenuItem_FormPlain;
    private javax.swing.JMenuItem jMenuItem_H1;
    private javax.swing.JMenuItem jMenuItem_H2;
    private javax.swing.JMenuItem jMenuItem_H3;
    private javax.swing.JMenuItem jMenuItem_H4;
    private javax.swing.JMenuItem jMenuItem_H5;
    private javax.swing.JMenuItem jMenuItem_H6;
    private javax.swing.JMenuItem jMenuItem_HorizonLine;
    private javax.swing.JMenuItem jMenuItem_IMG;
    private javax.swing.JMenuItem jMenuItem_Link;
    private javax.swing.JMenuItem jMenuItem_Paragraoh;
    private javax.swing.JMenuItem jMenuItem_Title;
    private javax.swing.JMenuItem jMenu_Metal;
    private javax.swing.JMenuItem jMenu_Motif;
    private javax.swing.JMenuItem jMenu_Nimbus;
    private javax.swing.JMenu jMenu_Style;
    private javax.swing.JMenuItem jMenu_Windows;
    private javax.swing.JMenuItem jMenu_WindowsClassic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Control;
    private javax.swing.JPanel jPanel_Default;
    private javax.swing.JPanel jPanel_Default_HTML;
    private javax.swing.JPanel jPanel_Heading;
    private javax.swing.JPanel jPanel_Image;
    private javax.swing.JPanel jPanel_Link;
    private javax.swing.JPanel jPanel_Paragraph;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JScrollPane jTab_Preview;
    private javax.swing.JScrollPane jTab_Source;
    private javax.swing.JTextPane jTextPane_Source;
    private javax.swing.JToolBar jToolBar_Font;
    private javax.swing.JToolBar jToolBar_Main;
    private javax.swing.JButton jbut_AlignCenter;
    private javax.swing.JButton jbut_AlignFull;
    private javax.swing.JButton jbut_AlignLeft;
    private javax.swing.JButton jbut_AlignRight;
    private javax.swing.JButton jbut_Browser;
    private javax.swing.JButton jbut_NewFile;
    private javax.swing.JButton jbut_OpenFile;
    private javax.swing.JButton jbut_SaveFile;
    private javax.swing.JMenuItem jmenu_Copy;
    private javax.swing.JMenu jmenu_Edit;
    private javax.swing.JMenuItem jmenu_Exit;
    private javax.swing.JMenu jmenu_File;
    private javax.swing.JMenu jmenu_Help;
    private javax.swing.JMenuItem jmenu_Paste;
    private javax.swing.JMenuItem jmenu_newFile;
    private javax.swing.JMenuItem jmenu_openFile;
    private javax.swing.JMenuItem jmenu_saveFile;
    private javax.swing.JMenuItem jmenu_showAbout;
    private javax.swing.JPanel jpan_Editor;
    private javax.swing.JPanel jpan_Main;
    private javax.swing.JTabbedPane jtab_Main;
    // End of variables declaration//GEN-END:variables
}
