/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cis272_project;

import com.sun.java.swing.plaf.motif.MotifLookAndFeel;
import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.LookAndFeel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.metal.MetalLookAndFeel;

/**
 *
 * @author GW
 */
public class FrameMain extends javax.swing.JFrame {
    /**
     * Creates new form FrameMain
     */
    private static final String TITLE = "W.E.B. EDITOR";
    
    private JFileChooser chooser;
    private Clipboard clipBoard;
    private String fileName;
    
    public FrameMain() {
        init();
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpan_Main = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jpan_Editor = new javax.swing.JPanel();
        jtab_Main = new javax.swing.JTabbedPane();
        jTab_Editor = new javax.swing.JScrollPane();
        jTextPane_Editor = new javax.swing.JTextPane();
        jTab_Source = new javax.swing.JScrollPane();
        jTextPane_Source = new javax.swing.JTextPane();
        jTab_Preview = new javax.swing.JScrollPane();
        jEditorPane_Preview = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenu_File = new javax.swing.JMenu();
        jmenu_newFile = new javax.swing.JMenuItem();
        jmenu_openFile = new javax.swing.JMenuItem();
        jmenu_saveFile = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmenu_Exit = new javax.swing.JMenuItem();
        jmenu_Edit = new javax.swing.JMenu();
        jmenu_Copy = new javax.swing.JMenuItem();
        jmenu_Paste = new javax.swing.JMenuItem();
        jmenu_Help = new javax.swing.JMenu();
        jMenu_Style = new javax.swing.JMenu();
        jMenu_Nimbus = new javax.swing.JMenuItem();
        jMenu_Metal = new javax.swing.JMenuItem();
        jMenu_Motif = new javax.swing.JMenuItem();
        jMenu_WindowsClassic = new javax.swing.JMenuItem();
        jMenu_Windows = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmenu_showAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 800));

        jPanel1.setBackground(java.awt.SystemColor.activeCaptionBorder);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );

        jPanel2.setBackground(java.awt.SystemColor.activeCaptionBorder);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );

        jtab_Main.setDoubleBuffered(true);

        jTab_Editor.setViewportView(jTextPane_Editor);

        jtab_Main.addTab("Editor", jTab_Editor);

        jTab_Source.setViewportView(jTextPane_Source);

        jtab_Main.addTab("Source", jTab_Source);

        jTab_Preview.setViewportView(jEditorPane_Preview);

        jtab_Main.addTab("Preview", jTab_Preview);

        javax.swing.GroupLayout jpan_EditorLayout = new javax.swing.GroupLayout(jpan_Editor);
        jpan_Editor.setLayout(jpan_EditorLayout);
        jpan_EditorLayout.setHorizontalGroup(
            jpan_EditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtab_Main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        jpan_EditorLayout.setVerticalGroup(
            jpan_EditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtab_Main, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jtab_Main.getAccessibleContext().setAccessibleName("tab_Preview");

        javax.swing.GroupLayout jpan_MainLayout = new javax.swing.GroupLayout(jpan_Main);
        jpan_Main.setLayout(jpan_MainLayout);
        jpan_MainLayout.setHorizontalGroup(
            jpan_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpan_Editor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpan_MainLayout.setVerticalGroup(
            jpan_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpan_Editor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jmenu_File.setText("File");

        jmenu_newFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jmenu_newFile.setText("New File");
        jmenu_File.add(jmenu_newFile);

        jmenu_openFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jmenu_openFile.setText("Open File");
        jmenu_openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_openFileActionPerformed(evt);
            }
        });
        jmenu_File.add(jmenu_openFile);

        jmenu_saveFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmenu_saveFile.setText("Save File");
        jmenu_File.add(jmenu_saveFile);
        jmenu_File.add(jSeparator1);

        jmenu_Exit.setText("Exit");
        jmenu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_ExitActionPerformed(evt);
            }
        });
        jmenu_File.add(jmenu_Exit);

        jMenuBar1.add(jmenu_File);

        jmenu_Edit.setText("Edit");

        jmenu_Copy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmenu_Copy.setText("Copy");
        jmenu_Copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_CopyActionPerformed(evt);
            }
        });
        jmenu_Edit.add(jmenu_Copy);

        jmenu_Paste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jmenu_Paste.setText("Paste");
        jmenu_Paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_PasteActionPerformed(evt);
            }
        });
        jmenu_Edit.add(jmenu_Paste);

        jMenuBar1.add(jmenu_Edit);

        jmenu_Help.setText("Help");

        jMenu_Style.setText("Style");

        jMenu_Nimbus.setText("Nimbus");
        jMenu_Nimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_NimbusActionPerformed(evt);
            }
        });
        jMenu_Style.add(jMenu_Nimbus);

        jMenu_Metal.setText("Metal");
        jMenu_Metal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_MetalActionPerformed(evt);
            }
        });
        jMenu_Style.add(jMenu_Metal);

        jMenu_Motif.setText("Motif");
        jMenu_Motif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_MotifActionPerformed(evt);
            }
        });
        jMenu_Style.add(jMenu_Motif);

        jMenu_WindowsClassic.setText("WindowsClassic");
        jMenu_WindowsClassic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_WindowsClassicActionPerformed(evt);
            }
        });
        jMenu_Style.add(jMenu_WindowsClassic);

        jMenu_Windows.setText("Windows");
        jMenu_Windows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_WindowsActionPerformed(evt);
            }
        });
        jMenu_Style.add(jMenu_Windows);

        jmenu_Help.add(jMenu_Style);
        jmenu_Help.add(jSeparator2);

        jmenu_showAbout.setText("About");
        jmenu_showAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_showAboutActionPerformed(evt);
            }
        });
        jmenu_Help.add(jmenu_showAbout);

        jMenuBar1.add(jmenu_Help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpan_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpan_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenu_openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_openFileActionPerformed
        //--Open File system
        chooser.setFileFilter(new FileNameExtensionFilter("HTML and CSS", "HTML" ,"CSS"));
        int r_Value = chooser.showOpenDialog(this);
        if(r_Value == JFileChooser.APPROVE_OPTION){
            System.out.println("You chose to open this file: " +
            chooser.getSelectedFile().getName());
        }
    }//GEN-LAST:event_jmenu_openFileActionPerformed

    private void jmenu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_ExitActionPerformed
        // A quick close operation TODO: ask to save before quitting.
        System.exit(0);
    }//GEN-LAST:event_jmenu_ExitActionPerformed

    private void jmenu_showAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_showAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "This software was developed by Daniel Sega Mattos as a open-source project.", "About: W.E.B. Editor", WIDTH,null);
    }//GEN-LAST:event_jmenu_showAboutActionPerformed

    private void jmenu_PasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_PasteActionPerformed
        String result = "No Value";
        clipBoard = Toolkit.getDefaultToolkit().getSystemClipboard();
        Transferable transClip = clipBoard.getContents(null);
        
        if(transClip != null){
            if(transClip.isDataFlavorSupported(DataFlavor.stringFlavor)){
                try{
                    result = (String) transClip.getTransferData(DataFlavor.stringFlavor);
                }catch(UnsupportedFlavorException | IOException e){
                    e.printStackTrace();
                }
            }
        }
        jTextPane_Editor.setText(result);
    }//GEN-LAST:event_jmenu_PasteActionPerformed

    private void jmenu_CopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_CopyActionPerformed
        //TODO: Select text
        clipBoard = Toolkit.getDefaultToolkit().getSystemClipboard();
        Transferable tText = new StringSelection("test");
        clipBoard.setContents(tText, null);
    }//GEN-LAST:event_jmenu_CopyActionPerformed

    private void jMenu_MetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_MetalActionPerformed
        changeLookAndFeel(new MetalLookAndFeel());
    }//GEN-LAST:event_jMenu_MetalActionPerformed

    private void jMenu_NimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_NimbusActionPerformed
        changeLookAndFeel(new javax.swing.plaf.nimbus.NimbusLookAndFeel());
    }//GEN-LAST:event_jMenu_NimbusActionPerformed

    private void jMenu_MotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_MotifActionPerformed
        changeLookAndFeel(new MotifLookAndFeel());
    }//GEN-LAST:event_jMenu_MotifActionPerformed

    private void jMenu_WindowsClassicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_WindowsClassicActionPerformed
        changeLookAndFeel(new WindowsClassicLookAndFeel());
    }//GEN-LAST:event_jMenu_WindowsClassicActionPerformed

    private void jMenu_WindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_WindowsActionPerformed
        changeLookAndFeel(new WindowsLookAndFeel());
    }//GEN-LAST:event_jMenu_WindowsActionPerformed
    
    private void changeLookAndFeel(LookAndFeel laf){
        try {
            UIManager.setLookAndFeel(laf);
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FrameMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    //--My Initiallizer
    private void init(){
        setTitle(TITLE);
        chooser = new JFileChooser();  
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane_Preview;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenu_Metal;
    private javax.swing.JMenuItem jMenu_Motif;
    private javax.swing.JMenuItem jMenu_Nimbus;
    private javax.swing.JMenu jMenu_Style;
    private javax.swing.JMenuItem jMenu_Windows;
    private javax.swing.JMenuItem jMenu_WindowsClassic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JScrollPane jTab_Editor;
    private javax.swing.JScrollPane jTab_Preview;
    private javax.swing.JScrollPane jTab_Source;
    private javax.swing.JTextPane jTextPane_Editor;
    private javax.swing.JTextPane jTextPane_Source;
    private javax.swing.JMenuItem jmenu_Copy;
    private javax.swing.JMenu jmenu_Edit;
    private javax.swing.JMenuItem jmenu_Exit;
    private javax.swing.JMenu jmenu_File;
    private javax.swing.JMenu jmenu_Help;
    private javax.swing.JMenuItem jmenu_Paste;
    private javax.swing.JMenuItem jmenu_newFile;
    private javax.swing.JMenuItem jmenu_openFile;
    private javax.swing.JMenuItem jmenu_saveFile;
    private javax.swing.JMenuItem jmenu_showAbout;
    private javax.swing.JPanel jpan_Editor;
    private javax.swing.JPanel jpan_Main;
    private javax.swing.JTabbedPane jtab_Main;
    // End of variables declaration//GEN-END:variables
}
